### ISSUE TITLE
Table cells not vertically aligned

### ISSUE THREAD

**Issue by frewsxcv** [servo/servo#10621]
# HTML

```html
<style>
td {
  height: 5em;
  width: 5em;
  border: 1px solid black;
}
</style>
<table>
  <tr>
    <td>Foo</td>
  </tr>
</table>
```

# Chrome

![screen shot 2016-04-14 at 7 12 06 pm](https://cloud.githubusercontent.com/assets/416575/14546681/2c67f5b2-0275-11e6-99df-2cf7df9a927c.png)

# Servo

<img width="912" alt="screen shot 2016-04-14 at 7 11 51 pm" src="https://cloud.githubusercontent.com/assets/416575/14546682/342050b0-0275-11e6-99e9-8995bab0cb9b.png">

**Comment by frewsxcv** [comment]
This is probably because we don't have

```css
thead, tbody, tfoot, table > tr { vertical-align: middle; }
tr, td, th { vertical-align: inherit; }
```

in the [`presentational_hints.css`](https://github.com/servo/servo/blob/master/resources/presentational-hints.css) file.
