### ISSUE TITLE
Wrong block width when using negative margins and overflow

### ISSUE THREAD

**Issue by fvsch** [servo/servo#13299]
The width of a `display: block` element with styles such as:

```css
div {
  width: auto;
  margin-left: -20px;
  margin-right: -20px;
  overflow: auto;
}
```

will be wrong in Servo. It will be 40px narrower than the same block with `overflow: visible`. This problem happens with all `overflow` values other than `visible`.

Here’s a reduced test case:
http://fvsch.com/code/bugs/servo-negative-margins-width/

- Expected behavior: in each section, all blue blocks should have the same width.
- Actual result: in each section, only the first block (`overflow:visible`) has the correct width, all others are too short.

Tested with Servo Nightly 0.0.1-e3d946b (2016-09-16 I think?).
