### ISSUE TITLE
Link icons do not scroll horizontally with page

### ISSUE THREAD

**Issue by jdm** [servo/servo#15502]
Visit https://developer.mozilla.org/en-US/docs/Web/Demos_of_open_web_technologies and scroll the page horizontally. The external link icons remain rendered in their initial positions while the rest of the page scrolls around them.

**Comment by jdm** [comment]
I haven't been able to make a minimal testcase yet, but the icons are generated via:
```css
a::before {
  content: '\f08e';
  display: inline-block;
  opacity: 0.5;
}
```
