### ISSUE TITLE
Malformed Cargo.toml in servo_tidy_tests prevents using servo as a git dependency (again)

### ISSUE THREAD

**Issue by kdy1997** [servo/servo#16149]
Similar issue: #15737

Cargo now requires [lib], or [[bin]]

Adding below to `servo_tidy_tests/Cargo.toml` fixes it.

```toml
[lib]
path = "lib.rs"
```
