### ISSUE TITLE
Line height is not properly calculated

### ISSUE THREAD

**Issue by blacksvk** [servo/servo#16476]
Line height is smaller compared to another browsers when the "line-height" css property is not specified.
Tested on Windows 8.1 x64.

```
<html>
	<style>
		.utext {
			font-size: 70px;
			font-family: 'Tahoma', 'Ubuntu';
		}
	</style>
	<div class="utext">
		This is a test<br>
		servo servo
	</div>
</html>
```

![font-size](https://cloud.githubusercontent.com/assets/10187350/25064915/abdc2768-2205-11e7-9c4b-ef273a822322.png)

**Comment by pyfisch** [comment]
Can not reproduce on Ubuntu 16.04. Why is the font family either Tahoma or Ubuntu? It may help to remove one font.

**Comment by atouchet** [comment]
I get the same output as @blacksvk in Windows 10.

**Comment by blacksvk** [comment]
@pyfisch It seems it does not matter which font I set.

**Comment by sciguyryan** [comment]
I can confirm that this issue definitely exists on Windows 10. The font also doesn't seem to affect the results at all.

**Comment by jdm** [comment]
This may be an example of #16034 being an incomplete solution.

**Comment by codec-abc** [comment]
jdm is probably right. If someone wants to take a look my [previous comment](https://github.com/servo/servo/pull/15937#issuecomment-286513712) may be a good starting point. I might take a look at it if I have enough time.

**Comment by imiuka** [comment]
yeah. to further illustrate, the current code returns these font metrics for segoe ui at 40px. if you look closely, the current algorithm for windows reports a line gap of 21px for a 40px font size, which obviously cannot be correct.

![uh oh](https://user-images.githubusercontent.com/975570/27169925-589f0452-51ef-11e7-89c4-3e093675350e.png)

```yaml
FontMetrics {
    underline_size:   0.9333333333333333px
    underline_offset: -3.4833333333333334px
    strikeout_size:   0.8px
    strikeout_offset: 10.35px
    leading:          15.15px
    x_height:         20px
    em_size:          40px
    ascent:           43.166666666666664px
    descent:          10.033333333333333px
    max_advance:      0px
    average_advance:  0px
    line_gap:         21.283333333333335px
}
```

(this is windows specific)

**Comment by codec-abc** [comment]
What you can do is dump the values of the struct returned by the DirectWrite API. As we already summing three fields in the struct to compute the baseline I would be suprised if we need to add more. Maybe it is a problem of sign in the line of the linegap value or a unit problem.

**Comment by hinaria** [comment]
should be fixed in #17340! :D

---
@codec-abc of course, that's is the obvious first step. in any case, it's fixed already!

```yaml
DWRITE_FONT_METRICS {
    designUnitsPerEm:       2048
    ascent:                 2210
    descent:                514
    lineGap:                0
    capHeight:              1434
    xHeight:                1024
    underlinePosition:      -178
    underlineThickness:     119
    strikethroughPosition:  530
    strikethroughThickness: 102
}
```
