### ISSUE TITLE
get some trouble with compile canvas components

### ISSUE THREAD

**Issue by Brooooooklyn** [servo/servo#19289]
I want build a node-canvas like project use components/canvas,
but got a compile error when I had my first try.

![image](https://user-images.githubusercontent.com/3468483/33000200-9fa8a286-cde1-11e7-9535-194066e28a9d.png)

### rustc version

![image](https://user-images.githubusercontent.com/3468483/33000260-f444f7fe-cde1-11e7-940c-cfa14911dfcf.png)

### cargo version
![image](https://user-images.githubusercontent.com/3468483/33000273-0403af28-cde2-11e7-9f72-7e0f51c83c50.png)

here is my test project: https://github.com/Brooooooklyn/node-servo-canvas

here is my `Cargo.toml`:

```toml
[package]
name = "node-servo-canvas"
version = "0.1.0"

[dependencies]
canvas = { path = "servo/components/canvas" }

```
