### ISSUE TITLE
No background image on http://bholley.net/

### ISSUE THREAD

**Issue by sviter** [servo/servo#19421]
Go to http://bholley.net/
No background image visible.
You can see background image in Firefox

**Comment by tigercosmos** [comment]
Might related to this?
```css
@media (max-width: 1000px) {
  body {
    background-image: url(images/chinacat_mid.jpg);
  }
}

@media (max-width: 420px) and (max-height: 750px) {
  body {
    background-image: url(images/chinacat_small.jpg);
  }
}

```
