### ISSUE TITLE
Make it possible to start a Windows TC task that enables a RDP connection

### ISSUE THREAD

**Issue by paulrouget** [servo/servo#26082]
We would not make that a default. Maybe just an option in decision_task.py or a new keyword for `try=windows`.

The idea would be to add the `rdpInfo` field as documented here: https://community-tc.services.mozilla.com/docs/reference/workers/generic-worker/multiuser-windows-payload and set the location of the json file to a private location.

It also needs a specific scope.

**Comment by paulrouget** [comment]
Necessary additions:

```yaml
scopes:
  - 'generic-worker:allow-rdp:proj-servo/win2016'
payload:
  rdpInfo: public/rdpInfo.json
```
