### ISSUE TITLE
Got a mostly working flatpak

### ISSUE THREAD

**Issue by BryanQuigley** [servo/servo#27942]
Some questions:
 * For whatever reason Ctrl-L doesn't work in the flatpak.  What's different about it?
 * Would you like a PR to commit the desktop file and metainfo.xml to this repo instead of having it live on flathubs ?
 * My current strategy is to build the flatpak from the the nightly builds- another option would be to build from the source code directly. Thoughts?

Previous Issue #12102

### Current code
Not ready for merging anywhere, but can already build a flatpak :).

org.servo.Servo.desktop:

```
[Desktop Entry]
Type=Application
Name=Servo
Comment=Rust based browser engine
Exec=servo
Icon=org.servo.Servo
Terminal=false
Categories=Network;WebBrowser;
```

org.servo.Servo.metainfo.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>org.servo.Servo</id>
  <url type="homepage">https://servo.org/</url>
  <url type="bugtracker">https://github.com/servo/servo/issues</url>
  
  <name>Servo</name>
  <summary>Servo is a browser engine written in Rust.</summary>
  
  <metadata_license>CC-BY-SA-4.0</metadata_license>
  <project_license>MPL-2.0</project_license>
  
  <recommends>
    <control>pointing</control>
    <control>keyboard</control>
    <control>gamepad</control>
  </recommends>
  
  <description>
    <p>
      Servo’s mission is to provide an independent, modular, embeddable web engine, which allows developers to deliver content and applications using web standards.
    </p>
    <p>
    Servo is written in Rust, and shares code with Mozilla Firefox and the wider Rust ecosystem. Since its creation in 2012, Servo has contributed to W3C/WHATWG web standards by reporting specification issues and submitting new cross-browser automated tests, and core team members have co-edited new standards that have been adopted by other browsers. As a result, the Servo project helps drive the entire web platform forward while building on a platform of reusable, modular technologies that implement web standards.
    </p>
  </description>
  
   <releases>
      <release version="0.0.1-638fa8b1e" date="2020-12-12" urgency="high">
        <url>https://download.servo.org/</url>
      </release>
  </releases>

  <content_rating type="oars-1.1" />

  <launchable type="desktop-id">org.servo.Servo.desktop</launchable>
  <screenshots>
    <screenshot type="default">
      <caption>Servo viewing servo.org</caption>
      <image>https://servo.org/img/screenshot-servo.png</image>
    </screenshot>
    <screenshot>
      <caption>Wikipedia</caption>
      <image>https://servo.org/img/screenshot-wikipedia.png</image>
    </screenshot>
  </screenshots>
</component>
```

org.servo.Servo.yaml

```
app-id: org.servo.Servo
runtime: org.freedesktop.Platform
runtime-version: '20.08'
sdk: org.freedesktop.Sdk
command: servo
finish-args:
  - --socket=x11
  - --socket=wayland
  - --device=dri
  - --socket=pulseaudio
  - --share=ipc
  - --share=network
modules:
  - name: servo
    buildsystem: simple
    build-commands:
       - mkdir -p /app/bin/resources/
       - cp -R resources/* /app/bin/resources/
       - install -D resources/servo.svg /app/share/icons/hicolor/scalable/apps/${FLATPAK_ID}.svg
      # servo_1024.png, servo_64.png, servo.ico
       - install -D servo /app/bin/servo
       - install -D org.servo.Servo.desktop /app/share/applications/${FLATPAK_ID}.desktop
       - install -D org.servo.Servo.metainfo.xml /app/share/metainfo/${FLATPAK_ID}.metainfo.xml
    sources:
      - type: archive
        url: https://download.servo.org/nightly/linux/servo-latest.tar.gz
        sha256: 544cbad0b614bff6683fbac6a769842f013bb7d79a0bad06fec995940b6eee79
        #https://download.servo.org/nightly/linux/servo-latest.tar.gz.sha256
      - type: file
        path: org.servo.Servo.desktop
      - type: file
        path: org.servo.Servo.metainfo.xml
```
