### ISSUE TITLE
Four quick check jobs are triggered for every pull request update

### ISSUE THREAD

**Issue by mrobinson** [servo/servo#29603]
I believe what is happening is that because `quick_check.yml` triggers on:

```
  pull_request:
  push:
    branches:
      ["**", "!master", "!auto", "!try", "!try-linux", "!try-mac", "!try-windows", "!try-wpt", "!dependabot/**"]
```

one set of quick check actions is triggered for the push to the pull request branch and another is triggered for the change to the pull request. Can this simply be the following?

```
 pull_request:
   types: [opened, synchronize]
```
cc @sagudev
