### ISSUE TITLE
build failed on arch linux

### ISSUE THREAD

**Issue by treeshateorcs** [servo/servo#30913]
the whole build log won't fit in a github comment, so here's an external link to it https://0x0.st/Hg_K.txt

**Comment by jdm** [comment]
This is caused by the newest version of llvm, and is addressed by https://github.com/rust-lang/rust-bindgen/pull/2667. We need a newer version of bindgen to be released, but you can add a cargo override in cargo.toml:

```toml
[patch.crates-io]
bindgen = { git = 'https://github.com/sagudev/rust-bindgen.git', branch="f16" }
```
