### ISSUE TITLE
Docs pushing fails when there are two close landings.

### ISSUE THREAD

**Issue by sagudev** [servo/servo#31716]
Second run fails due to non-atomic git operations: https://github.com/servo/servo/actions/runs/8314880076/job/22752579192#step:6:17

>   ! [remote rejected] main -> gh-pages (cannot lock ref 'refs/heads/gh-pages': is at 4e755596e357fa1a7acf04392c8b2752997f1fa8 but expected 7320d0ff1e08304334be15d8dc94b9e50ef144ff)

I use something like this in one of my personal repos:
```bash
until (git pull --rebase && git push origin2 HEAD:master)
do
    echo "Try again"
done
```

**Comment by sagudev** [comment]
or maybe limit concurrent number of docs building:
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```
