### ISSUE TITLE
Skip fonts we don't understand

### ISSUE THREAD

**Issue by kmcallister** [servo/servo#3866]
The rendering of

``` html
<head><link rel="stylesheet" href="foo.css"></head>
<body>hello</body>
```

varies between

``` css
body {
    font-family: monospace;
}
```

and

``` css
body {
    font-family: theworstfontever, monospace;
}
```
