### ISSUE TITLE
Permanent failure in /css21_dev/html4/font-family-013.htm and /css21_dev/html4/fonts-013.htm

### ISSUE THREAD

**Issue by jdm** [servo/servo#7625]
These tests are both using unicode characters, and the run which contained a failure showed the characters appearing as boxes.

The test itself is interesting:

``` css
   .a span.test { font: 4em "Ahem", "Times New Roman"; }
   .a span.control { font: 4em "Times New Roman"; }
   .b span.test { font: 4em "Ahem", "Arial"; }
   .b span.control { font: 4em "Arial"; }
   .c span.test { font: 4em "Ahem", "Courier New"; }
   .c span.control { font: 4em "Courier New"; }
```

It looks like it's assuming that Ahem should not be present??
